/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Liveness probe (process is up) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example alive */
              status: string;
              /** @example 2026-04-02T11:47:06.000Z */
              timestamp: string;
              /** @example 1.0.0 */
              version: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Readiness probe (dependencies are ready) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example healthy */
              status: string;
              /** @example connected */
              database: string;
              /** @example 2026-04-02T11:47:06.000Z */
              timestamp: string;
              /** @example 1.0.0 */
              version: string;
            };
          };
        };
        /** @description Readiness probe failed */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example healthy */
              status: string;
              /** @example connected */
              database: string;
              /** @example 2026-04-02T11:47:06.000Z */
              timestamp: string;
              /** @example 1.0.0 */
              version: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Backward-compatible readiness endpoint */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example healthy */
              status: string;
              /** @example connected */
              database: string;
              /** @example 2026-04-02T11:47:06.000Z */
              timestamp: string;
              /** @example 1.0.0 */
              version: string;
            };
          };
        };
        /** @description Backward-compatible readiness endpoint failed */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example healthy */
              status: string;
              /** @example connected */
              database: string;
              /** @example 2026-04-02T11:47:06.000Z */
              timestamp: string;
              /** @example 1.0.0 */
              version: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/oauth/:provider': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to OAuth provider */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/oauth/:provider/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          code?: string;
          state?: string;
        };
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to frontend with tokens */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/methods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Get enabled authentication methods */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              authMode: 'local' | 'oauth' | 'both';
              local: boolean;
              oauth: {
                enabled: boolean;
                providers: {
                  google: boolean;
                  github: boolean;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterInput'];
        };
      };
      responses: {
        /** @description Registration successful */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: {
                id: string;
                email: string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginInput'];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: {
                id: string;
                email: string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token refresh successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: {
                id: string;
                email: string;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logout successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Get current user profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              userId: string;
              /** Format: email */
              email: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bbs/threads': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of all threads */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              threads: components['schemas']['Thread'][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateThreadInput'];
        };
      };
      responses: {
        /** @description Thread created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Thread'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bbs/threads/:id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The thread detail with comments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              thread: components['schemas']['Thread'];
            };
          };
        };
        /** @description Thread not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bbs/threads/:id/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateCommentInput'];
        };
      };
      responses: {
        /** @description Comment created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Comment'];
          };
        };
        /** @description Thread not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/vitals/blood-pressure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 血圧記録一覧 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              records: components['schemas']['BloodPressureRecord'][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateBloodPressureInput'];
        };
      };
      responses: {
        /** @description 既存と同一の外部 ID / 値ハッシュの場合は既存レコードを返す */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['BloodPressureRecord'];
              duplicate: boolean;
            };
          };
        };
        /** @description 新規作成 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['BloodPressureRecord'];
              duplicate: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/vitals/blood-pressure/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 血圧記録 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BloodPressureRecord'];
          };
        };
        /** @description 他ユーザーのデータ */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: date-time
             * @example 2026-04-07T08:30:00.000Z
             */
            recordedAt?: string;
            /** @example Asia/Tokyo */
            timeZone?: string;
            /** @example healthkit:sample:123 */
            externalId?: string;
            /** @description 重複排除用 SHA-256 hex */
            valueHash?: string;
            inputSource?: components['schemas']['HealthInputSource'];
            /** @example apple_health */
            syncSource?: string;
            memo?: string;
            /** @example 120 */
            systolic?: number;
            /** @example 80 */
            diastolic?: number;
            /** @example 72 */
            pulse?: number;
            period?: components['schemas']['BloodPressurePeriod'];
          };
        };
      };
      responses: {
        /** @description 更新後の血圧記録 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BloodPressureRecord'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 削除成功 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/vitals/blood-glucose': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 血糖値記録一覧 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              records: components['schemas']['BloodGlucoseRecord'][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateBloodGlucoseInput'];
        };
      };
      responses: {
        /** @description 重複のため既存レコードを返却 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['BloodGlucoseRecord'];
              duplicate: boolean;
            };
          };
        };
        /** @description 血糖値記録を新規作成 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['BloodGlucoseRecord'];
              duplicate: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/vitals/blood-glucose/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 血糖値記録 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BloodGlucoseRecord'];
          };
        };
        /** @description 他ユーザーのデータ */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: date-time
             * @example 2026-04-07T08:30:00.000Z
             */
            recordedAt?: string;
            /** @example Asia/Tokyo */
            timeZone?: string;
            /** @example healthkit:sample:123 */
            externalId?: string;
            /** @description 重複排除用 SHA-256 hex */
            valueHash?: string;
            inputSource?: components['schemas']['HealthInputSource'];
            /** @example apple_health */
            syncSource?: string;
            memo?: string;
            /** @example 95 */
            value?: number;
            unit?: components['schemas']['BloodGlucoseUnit'];
            timing?: components['schemas']['BloodGlucoseTiming'];
          };
        };
      };
      responses: {
        /** @description 更新後の血糖値記録 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BloodGlucoseRecord'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 削除成功 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/nutrition/meals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 食事記録一覧 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              records: components['schemas']['MealRecord'][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateMealInput'];
        };
      };
      responses: {
        /** @description 重複のため既存レコードを返却 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['MealRecord'];
              duplicate: boolean;
            };
          };
        };
        /** @description 食事記録を新規作成 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              record: components['schemas']['MealRecord'];
              duplicate: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/activity/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ActivitySyncBody'];
        };
      };
      responses: {
        /** @description 活動データの同期結果 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              records: components['schemas']['ActivityRecord'][];
              inserted: number;
              duplicates: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/activity/daily': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          date?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 指定日の活動集計 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 2026-04-07 */
              date: string;
              stepsTotal: number;
              activeMinutesTotal: number;
              caloriesBurnedTotal: number;
              records: components['schemas']['ActivityRecord'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/activity/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 期間内の運動記録一覧 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              records: components['schemas']['ActivityRecord'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/summary/daily': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          date?: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 日次健康サマリ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DailySummaryResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/summary/weekly': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          weekStart: string;
          timeZone?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 週次サマリ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              weekStart: string;
              weekEnd: string;
              days: {
                date: string;
                stepsTotal: number;
                mealCount: number;
              }[];
              avgSystolic: number | null;
              avgDiastolic: number | null;
              bloodPressureSampleCount: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/summary/monthly': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          yearMonth: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 月次サマリ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              yearMonth: string;
              stepsTotal: number;
              mealCount: number;
              avgSteps: number;
              days: {
                date: string;
                stepsTotal: number;
                mealCount: number;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/nutrition/meals/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: date-time
             * @example 2026-04-07T08:30:00.000Z
             */
            recordedAt?: string;
            /** @example Asia/Tokyo */
            timeZone?: string;
            /** @example healthkit:sample:123 */
            externalId?: string;
            /** @description 重複排除用 SHA-256 hex */
            valueHash?: string;
            inputSource?: components['schemas']['HealthInputSource'];
            /** @example apple_health */
            syncSource?: string;
            memo?: string;
            /** @example 玄米ごはん、味噌汁、焼き魚 */
            items?: string;
            /** @example 450 */
            estimatedCalories?: number;
          };
        };
      };
      responses: {
        /** @description 更新後の食事記録 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MealRecord'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 削除成功 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterInput: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example password123 */
      password: string;
      /** @example John Doe */
      name: string;
    };
    LoginInput: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example password123 */
      password: string;
    };
    Thread: {
      /** @example thread-uuid */
      id: string;
      /** @example My Thread */
      title: string;
      /** @example Thread content */
      content: string;
      /** @example user-uuid */
      authorId: string;
      /** @example 2026-04-02T11:47:06.000Z */
      createdAt: string;
      /** @example 2026-04-02T11:47:06.000Z */
      updatedAt: string;
      comments?: components['schemas']['Comment'][];
    };
    Comment: {
      /** @example comment-uuid */
      id: string;
      /** @example thread-uuid */
      threadId: string;
      /** @example null */
      parentId: string | null;
      /** @example My comment */
      content: string;
      /** @example user-uuid */
      authorId: string;
      /** @example 2026-04-02T11:47:06.000Z */
      createdAt: string;
      /** @example 2026-04-02T11:47:06.000Z */
      updatedAt: string;
    };
    CreateThreadInput: {
      /** @example My First Thread */
      title: string;
      /** @example Hello, this is the content of my first thread. */
      content: string;
    };
    CreateCommentInput: {
      /** @example Great thread! */
      content: string;
      /**
       * Format: uuid
       * @example uuid-of-parent-comment
       */
      parentId?: string;
    };
    BloodPressureRecord: {
      /** Format: uuid */
      id: string;
      recordedAt: string;
      systolic: number;
      diastolic: number;
      pulse: number | null;
      period: components['schemas']['BloodPressurePeriod'];
      externalId: string | null;
      valueHash: string | null;
      inputSource: components['schemas']['HealthInputSource'];
      syncSource: string | null;
      memo: string | null;
      createdAt: string;
      updatedAt: string;
    };
    /** @enum {string} */
    BloodPressurePeriod: 'morning' | 'evening' | 'other';
    /** @enum {string} */
    HealthInputSource: 'manual' | 'device' | 'import' | 'api';
    CreateBloodPressureInput: {
      /**
       * Format: date-time
       * @example 2026-04-07T08:30:00.000Z
       */
      recordedAt: string;
      /** @example Asia/Tokyo */
      timeZone?: string;
      /** @example healthkit:sample:123 */
      externalId?: string;
      /** @description 重複排除用 SHA-256 hex */
      valueHash?: string;
      inputSource?: components['schemas']['HealthInputSource'];
      /** @example apple_health */
      syncSource?: string;
      memo?: string;
      /** @example 120 */
      systolic: number;
      /** @example 80 */
      diastolic: number;
      /** @example 72 */
      pulse?: number;
      period: components['schemas']['BloodPressurePeriod'];
    };
    BloodGlucoseRecord: {
      /** Format: uuid */
      id: string;
      recordedAt: string;
      value: number;
      unit: components['schemas']['BloodGlucoseUnit'];
      timing: components['schemas']['BloodGlucoseTiming'];
      externalId: string | null;
      valueHash: string | null;
      inputSource: components['schemas']['HealthInputSource'];
      syncSource: string | null;
      memo: string | null;
      createdAt: string;
      updatedAt: string;
    };
    /** @enum {string} */
    BloodGlucoseUnit: 'mg_dl' | 'mmol_l';
    /** @enum {string} */
    BloodGlucoseTiming: 'fasting' | 'postprandial' | 'random';
    CreateBloodGlucoseInput: {
      /**
       * Format: date-time
       * @example 2026-04-07T08:30:00.000Z
       */
      recordedAt: string;
      /** @example Asia/Tokyo */
      timeZone?: string;
      /** @example healthkit:sample:123 */
      externalId?: string;
      /** @description 重複排除用 SHA-256 hex */
      valueHash?: string;
      inputSource?: components['schemas']['HealthInputSource'];
      /** @example apple_health */
      syncSource?: string;
      memo?: string;
      /** @example 95 */
      value: number;
      unit: components['schemas']['BloodGlucoseUnit'];
      timing: components['schemas']['BloodGlucoseTiming'];
    };
    MealRecord: {
      /** Format: uuid */
      id: string;
      recordedAt: string;
      items: string;
      estimatedCalories: number | null;
      externalId: string | null;
      valueHash: string | null;
      inputSource: components['schemas']['HealthInputSource'];
      syncSource: string | null;
      memo: string | null;
      createdAt: string;
      updatedAt: string;
    };
    CreateMealInput: {
      /**
       * Format: date-time
       * @example 2026-04-07T08:30:00.000Z
       */
      recordedAt: string;
      /** @example Asia/Tokyo */
      timeZone?: string;
      /** @example healthkit:sample:123 */
      externalId?: string;
      /** @description 重複排除用 SHA-256 hex */
      valueHash?: string;
      inputSource?: components['schemas']['HealthInputSource'];
      /** @example apple_health */
      syncSource?: string;
      memo?: string;
      /** @example 玄米ごはん、味噌汁、焼き魚 */
      items: string;
      /** @example 450 */
      estimatedCalories?: number;
    };
    ActivityRecord: {
      /** Format: uuid */
      id: string;
      recordedAt: string;
      steps: number | null;
      activeMinutes: number | null;
      caloriesBurned: number | null;
      externalId: string | null;
      valueHash: string | null;
      inputSource: components['schemas']['HealthInputSource'];
      syncSource: string | null;
      memo: string | null;
      createdAt: string;
      updatedAt: string;
    };
    ActivitySyncBody: {
      items: components['schemas']['ActivitySyncItem'][];
      syncSource?: string;
    };
    ActivitySyncItem: {
      /**
       * Format: date-time
       * @example 2026-04-07T08:30:00.000Z
       */
      recordedAt: string;
      /** @example Asia/Tokyo */
      timeZone?: string;
      /** @example healthkit:sample:123 */
      externalId?: string;
      /** @description 重複排除用 SHA-256 hex */
      valueHash?: string;
      inputSource?: components['schemas']['HealthInputSource'];
      /** @example apple_health */
      syncSource?: string;
      memo?: string;
      steps?: number;
      activeMinutes?: number;
      caloriesBurned?: number;
    };
    DailySummaryResponse: {
      date: string;
      stepsTotal: number;
      activeMinutesTotal: number;
      activityCaloriesTotal: number;
      mealCount: number;
      latestBloodPressure: components['schemas']['BloodPressureRecord'] & unknown;
      latestBloodGlucose: components['schemas']['BloodGlucoseRecord'] & unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
