/**
 * 回答パターンシードデータ
 * 患者の多様な回答パターンに対する正規化ルール
 */

export interface AnswerPatternSeed {
  questionKey: string;
  patternType: 'standard' | 'variation' | 'edge_case';
  inputPattern: string;
  normalizedValue: string;
  dataType: 'string' | 'number' | 'boolean' | 'date' | 'array';
  confidence: number;
  frequency: number;
}

export const answerPatternSeeds: AnswerPatternSeed[] = [
  // ============ 氏名パターン ============
  {
    questionKey: 'patient_name',
    patternType: 'standard',
    inputPattern: '^(.+)（(.+)）$',
    normalizedValue: '$1（$2）',
    dataType: 'string',
    confidence: 1.0,
    frequency: 150,
  },
  {
    questionKey: 'patient_name',
    patternType: 'variation',
    inputPattern: '^(.+)\\((.+)\\)$',
    normalizedValue: '$1（$2）',
    dataType: 'string',
    confidence: 0.95,
    frequency: 80,
  },
  {
    questionKey: 'patient_name',
    patternType: 'variation',
    inputPattern: '^(.+)\\s+(.+)です?$',
    normalizedValue: '$1（$2）',
    dataType: 'string',
    confidence: 0.9,
    frequency: 60,
  },
  {
    questionKey: 'patient_name',
    patternType: 'edge_case',
    inputPattern: '^(.+)と申します。読み方は(.+)です。?$',
    normalizedValue: '$1（$2）',
    dataType: 'string',
    confidence: 0.95,
    frequency: 20,
  },

  // ============ 性別パターン ============
  {
    questionKey: 'gender',
    patternType: 'standard',
    inputPattern: '^男性$',
    normalizedValue: '男性',
    dataType: 'string',
    confidence: 1.0,
    frequency: 200,
  },
  {
    questionKey: 'gender',
    patternType: 'standard',
    inputPattern: '^女性$',
    normalizedValue: '女性',
    dataType: 'string',
    confidence: 1.0,
    frequency: 180,
  },
  {
    questionKey: 'gender',
    patternType: 'variation',
    inputPattern: '^男$',
    normalizedValue: '男性',
    dataType: 'string',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'gender',
    patternType: 'variation',
    inputPattern: '^女$',
    normalizedValue: '女性',
    dataType: 'string',
    confidence: 0.95,
    frequency: 45,
  },
  {
    questionKey: 'gender',
    patternType: 'variation',
    inputPattern: '^(男性|女性)です$',
    normalizedValue: '$1',
    dataType: 'string',
    confidence: 0.98,
    frequency: 120,
  },
  {
    questionKey: 'gender',
    patternType: 'edge_case',
    inputPattern: '^(male|Male)$',
    normalizedValue: '男性',
    dataType: 'string',
    confidence: 0.9,
    frequency: 10,
  },
  {
    questionKey: 'gender',
    patternType: 'edge_case',
    inputPattern: '^(female|Female)$',
    normalizedValue: '女性',
    dataType: 'string',
    confidence: 0.9,
    frequency: 8,
  },

  // ============ 生年月日パターン ============
  {
    questionKey: 'birth_date',
    patternType: 'standard',
    inputPattern: '^(\\d{4})年(\\d{1,2})月(\\d{1,2})日$',
    normalizedValue: '$1-$2-$3',
    dataType: 'date',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'birth_date',
    patternType: 'variation',
    inputPattern: '^(\\d{4})/(\\d{1,2})/(\\d{1,2})$',
    normalizedValue: '$1-$2-$3',
    dataType: 'date',
    confidence: 0.95,
    frequency: 80,
  },
  {
    questionKey: 'birth_date',
    patternType: 'variation',
    inputPattern: '^(\\d{4})-(\\d{1,2})-(\\d{1,2})$',
    normalizedValue: '$1-$2-$3',
    dataType: 'date',
    confidence: 1.0,
    frequency: 60,
  },
  {
    questionKey: 'birth_date',
    patternType: 'edge_case',
    inputPattern: '^昭和(\\d{1,2})年(\\d{1,2})月(\\d{1,2})日$',
    normalizedValue: 'SHOWA_$1-$2-$3',
    dataType: 'date',
    confidence: 0.85,
    frequency: 40,
  },

  // ============ 電話番号パターン ============
  {
    questionKey: 'phone_number',
    patternType: 'standard',
    inputPattern: '^(0[789]0)-(\\d{4})-(\\d{4})$',
    normalizedValue: '$1$2$3',
    dataType: 'string',
    confidence: 1.0,
    frequency: 150,
  },
  {
    questionKey: 'phone_number',
    patternType: 'variation',
    inputPattern: '^(0[789]0)\\s?(\\d{4})\\s?(\\d{4})$',
    normalizedValue: '$1$2$3',
    dataType: 'string',
    confidence: 0.95,
    frequency: 70,
  },
  {
    questionKey: 'phone_number',
    patternType: 'variation',
    inputPattern: '^携帯は(0[789]0-?\\d{4}-?\\d{4})です?$',
    normalizedValue: '$1',
    dataType: 'string',
    confidence: 0.9,
    frequency: 30,
  },

  // ============ 体温パターン ============
  {
    questionKey: 'current_temperature',
    patternType: 'standard',
    inputPattern: '^(\\d{2}\\.\\d)度?$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 120,
  },
  {
    questionKey: 'current_temperature',
    patternType: 'variation',
    inputPattern: '^(\\d{2}\\.\\d)℃$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'current_temperature',
    patternType: 'variation',
    inputPattern: '^(\\d{2})度(\\d)分$',
    normalizedValue: '$1.$2',
    dataType: 'number',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'current_temperature',
    patternType: 'variation',
    inputPattern: '^(\\d{2})度くらい$',
    normalizedValue: '$1.0',
    dataType: 'number',
    confidence: 0.8,
    frequency: 30,
  },
  {
    questionKey: 'current_temperature',
    patternType: 'edge_case',
    inputPattern: '^熱は(\\d{2}\\.\\d)度です$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.9,
    frequency: 20,
  },

  // ============ 朝の体温パターン ============
  {
    questionKey: 'morning_temperature',
    patternType: 'standard',
    inputPattern: '^(\\d{2}\\.\\d)度でした$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 80,
  },
  {
    questionKey: 'morning_temperature',
    patternType: 'variation',
    inputPattern: '^朝は(\\d{2}\\.\\d)度$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 60,
  },
  {
    questionKey: 'morning_temperature',
    patternType: 'edge_case',
    inputPattern: '^あさ測ったら(\\d{2}\\.\\d)℃でした$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.9,
    frequency: 15,
  },

  // ============ 身長パターン ============
  {
    questionKey: 'height',
    patternType: 'standard',
    inputPattern: '^(\\d{3})cmです?$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'height',
    patternType: 'variation',
    inputPattern: '^(\\d{3})センチ$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'height',
    patternType: 'variation',
    inputPattern: '^身長は(\\d{3})cm$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'height',
    patternType: 'edge_case',
    inputPattern: '^1メートル(\\d{2})センチ$',
    normalizedValue: '1$1',
    dataType: 'number',
    confidence: 0.9,
    frequency: 20,
  },
  {
    questionKey: 'height',
    patternType: 'edge_case',
    inputPattern: '^(\\d{3})$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.8,
    frequency: 30,
  },

  // ============ 体重パターン ============
  {
    questionKey: 'weight',
    patternType: 'standard',
    inputPattern: '^(\\d{2,3})kgです?$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'weight',
    patternType: 'variation',
    inputPattern: '^(\\d{2,3})キロ$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 70,
  },
  {
    questionKey: 'weight',
    patternType: 'variation',
    inputPattern: '^体重は(\\d{2,3})kg$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'weight',
    patternType: 'variation',
    inputPattern: '^(\\d{2,3})キログラム$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.9,
    frequency: 20,
  },

  // ============ 発熱開始時期パターン ============
  {
    questionKey: 'fever_start_date',
    patternType: 'standard',
    inputPattern: '^昨日の(朝|昼|夕方|夜)からです?$',
    normalizedValue: '昨日$1',
    dataType: 'string',
    confidence: 0.95,
    frequency: 80,
  },
  {
    questionKey: 'fever_start_date',
    patternType: 'variation',
    inputPattern: '^(\\d+)日前の?(朝|昼|夕方|夜)?から?$',
    normalizedValue: '$1日前$2',
    dataType: 'string',
    confidence: 0.9,
    frequency: 60,
  },
  {
    questionKey: 'fever_start_date',
    patternType: 'variation',
    inputPattern: '^今朝から熱が出始めました$',
    normalizedValue: '今朝',
    dataType: 'string',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'fever_start_date',
    patternType: 'edge_case',
    inputPattern: '^一昨日の(.+)頃から発熱しています$',
    normalizedValue: '一昨日$1',
    dataType: 'string',
    confidence: 0.9,
    frequency: 20,
  },

  // ============ 症状パターン ============
  {
    questionKey: 'current_symptoms',
    patternType: 'standard',
    inputPattern: '^咳と喉の痛み、(それから|あと)?倦怠感があります$',
    normalizedValue: '["咳", "喉の痛み", "倦怠感"]',
    dataType: 'array',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'current_symptoms',
    patternType: 'variation',
    inputPattern: '^頭痛も?少しあります$',
    normalizedValue: '["頭痛"]',
    dataType: 'array',
    confidence: 0.9,
    frequency: 30,
  },
  {
    questionKey: 'current_symptoms',
    patternType: 'variation',
    inputPattern: '^咳、鼻水、関節痛$',
    normalizedValue: '["咳", "鼻水", "関節痛"]',
    dataType: 'array',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'current_symptoms',
    patternType: 'edge_case',
    inputPattern: '^特にありません$',
    normalizedValue: '["特になし"]',
    dataType: 'array',
    confidence: 1.0,
    frequency: 60,
  },
  {
    questionKey: 'current_symptoms',
    patternType: 'edge_case',
    inputPattern: '^咳がひどくて、(だるい|熱っぽい)感じがします$',
    normalizedValue: '["咳", "倦怠感"]',
    dataType: 'array',
    confidence: 0.85,
    frequency: 25,
  },

  // ============ ワクチン接種回数パターン ============
  {
    questionKey: 'vaccination_count',
    patternType: 'standard',
    inputPattern: '^(\\d+)回接種しています$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'vaccination_count',
    patternType: 'variation',
    inputPattern: '^(\\d+)回です$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 80,
  },
  {
    questionKey: 'vaccination_count',
    patternType: 'variation',
    inputPattern: '^(\\d+)回目まで受けました$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'vaccination_count',
    patternType: 'edge_case',
    inputPattern: '^まだ打っていません$',
    normalizedValue: '0',
    dataType: 'number',
    confidence: 1.0,
    frequency: 30,
  },
  {
    questionKey: 'vaccination_count',
    patternType: 'edge_case',
    inputPattern: '^(\\d+)回だけです$',
    normalizedValue: '$1',
    dataType: 'number',
    confidence: 0.9,
    frequency: 20,
  },

  // ============ ワクチン接種歴パターン ============
  {
    questionKey: 'vaccination_1st',
    patternType: 'standard',
    inputPattern: '^(\\d{4})年(\\d{1,2})月(\\d{1,2})日に(ファイザー|モデルナ|その他)です?$',
    normalizedValue: '$1-$2-$3_$4',
    dataType: 'string',
    confidence: 1.0,
    frequency: 80,
  },
  {
    questionKey: 'vaccination_1st',
    patternType: 'variation',
    inputPattern: '^(\\d{4})/(\\d{1,2})/(\\d{1,2})\\s+(ファイザー|モデルナ|その他)$',
    normalizedValue: '$1-$2-$3_$4',
    dataType: 'string',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'vaccination_1st',
    patternType: 'edge_case',
    inputPattern: '^まだ接種していません$',
    normalizedValue: '未接種',
    dataType: 'string',
    confidence: 1.0,
    frequency: 20,
  },

  // ============ 来院方法パターン ============
  {
    questionKey: 'transport_method',
    patternType: 'standard',
    inputPattern: '^車で来ました$',
    normalizedValue: '車',
    dataType: 'string',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'transport_method',
    patternType: 'variation',
    inputPattern: '^マイカーで来院しました$',
    normalizedValue: '車',
    dataType: 'string',
    confidence: 0.95,
    frequency: 30,
  },
  {
    questionKey: 'transport_method',
    patternType: 'variation',
    inputPattern: '^歩いて来ました$',
    normalizedValue: '徒歩',
    dataType: 'string',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'transport_method',
    patternType: 'edge_case',
    inputPattern: '^電車とバスで来ました$',
    normalizedValue: '公共交通機関',
    dataType: 'string',
    confidence: 0.9,
    frequency: 40,
  },

  // ============ PCR検査希望パターン ============
  {
    questionKey: 'pcr_test_desired',
    patternType: 'standard',
    inputPattern: '^はい、希望します$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 1.0,
    frequency: 80,
  },
  {
    questionKey: 'pcr_test_desired',
    patternType: 'variation',
    inputPattern: '^PCR検査をお願いします$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'pcr_test_desired',
    patternType: 'variation',
    inputPattern: '^検査したいです$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.9,
    frequency: 30,
  },
  {
    questionKey: 'pcr_test_desired',
    patternType: 'standard',
    inputPattern: '^いいえ、今回は結構です$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 1.0,
    frequency: 60,
  },
  {
    questionKey: 'pcr_test_desired',
    patternType: 'variation',
    inputPattern: '^特に希望しません$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 20,
  },

  // ============ 接触歴・既往歴パターン ============
  {
    questionKey: 'suspected_contact',
    patternType: 'standard',
    inputPattern: '^いいえ、していません$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 1.0,
    frequency: 120,
  },
  {
    questionKey: 'suspected_contact',
    patternType: 'variation',
    inputPattern: '^特に心当たりはありません$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 40,
  },
  {
    questionKey: 'suspected_contact',
    patternType: 'variation',
    inputPattern: '^はい、職場で感染者が出ました$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 30,
  },

  // ============ 慢性疾患治療パターン ============
  {
    questionKey: 'chronic_treatment',
    patternType: 'standard',
    inputPattern: '^はい、(高血圧|糖尿病|高脂血症)で内科に通院しています$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 60,
  },
  {
    questionKey: 'chronic_treatment',
    patternType: 'variation',
    inputPattern: '^(血圧|血糖)の薬を飲んでいます$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.9,
    frequency: 40,
  },
  {
    questionKey: 'chronic_treatment',
    patternType: 'standard',
    inputPattern: '^いいえ、特にありません$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 1.0,
    frequency: 100,
  },

  // ============ 市販薬服用パターン ============
  {
    questionKey: 'otc_medication',
    patternType: 'standard',
    inputPattern: '^はい、昨夜解熱剤を飲みました$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.95,
    frequency: 50,
  },
  {
    questionKey: 'otc_medication',
    patternType: 'variation',
    inputPattern: '^風邪薬を飲んでいます$',
    normalizedValue: 'true',
    dataType: 'boolean',
    confidence: 0.9,
    frequency: 30,
  },
  {
    questionKey: 'otc_medication',
    patternType: 'standard',
    inputPattern: '^いいえ、何も飲んでいません$',
    normalizedValue: 'false',
    dataType: 'boolean',
    confidence: 1.0,
    frequency: 80,
  },

  // ============ 薬剤名パターン ============
  {
    questionKey: 'medication_details',
    patternType: 'standard',
    inputPattern: '^(ロキソニン|バファリン|カロナール|イブ|ノーシン)です?$',
    normalizedValue: '$1',
    dataType: 'string',
    confidence: 1.0,
    frequency: 60,
  },
  {
    questionKey: 'medication_details',
    patternType: 'variation',
    inputPattern: '^解熱鎮痛剤（名前は覚えていません）$',
    normalizedValue: '解熱鎮痛剤（詳細不明）',
    dataType: 'string',
    confidence: 0.8,
    frequency: 20,
  },

  // ============ 生活習慣パターン ============
  {
    questionKey: 'drinking_habits',
    patternType: 'standard',
    inputPattern: '^飲みます$',
    normalizedValue: '飲む',
    dataType: 'string',
    confidence: 1.0,
    frequency: 80,
  },
  {
    questionKey: 'drinking_habits',
    patternType: 'variation',
    inputPattern: '^お酒は飲みません$',
    normalizedValue: '飲まない',
    dataType: 'string',
    confidence: 1.0,
    frequency: 100,
  },
  {
    questionKey: 'drinking_habits',
    patternType: 'variation',
    inputPattern: '^時々付き合い程度に$',
    normalizedValue: '時々飲む',
    dataType: 'string',
    confidence: 0.9,
    frequency: 40,
  },

  {
    questionKey: 'smoking_habits',
    patternType: 'standard',
    inputPattern: '^禁煙しました$',
    normalizedValue: '禁煙した',
    dataType: 'string',
    confidence: 1.0,
    frequency: 60,
  },
  {
    questionKey: 'smoking_habits',
    patternType: 'variation',
    inputPattern: '^タバコは吸いません$',
    normalizedValue: '吸わない',
    dataType: 'string',
    confidence: 1.0,
    frequency: 80,
  },
  {
    questionKey: 'smoking_habits',
    patternType: 'variation',
    inputPattern: '^(\\d+)年前にやめました$',
    normalizedValue: '禁煙した',
    dataType: 'string',
    confidence: 0.95,
    frequency: 40,
  },
];
