/**
 * 問診質問テンプレートシードデータ
 * 発熱患者問診台本に基づく構造化質問定義
 */

export interface QuestionTemplateSeed {
  stage: string;
  questionKey: string;
  questionText: string;
  questionType: 'free_text' | 'choice' | 'date' | 'number' | 'boolean';
  dataField: string;
  isRequired: boolean;
  order: number;
  aiContext: string;
  validationRules: any;
  followUpConditions?: any;
  answerExample1?: string;
  answerExample2?: string;
  answerExample3?: string;
  answerExample4?: string;
  answerExample5?: string;
  choices?: string[];
}

export const questionTemplateSeeds: QuestionTemplateSeed[] = [
  // ============ シーン1: アプリ開始・基本情報入力 ============
  {
    stage: 'basic_info',
    questionKey: 'patient_name',
    questionText:
      'まず、基本的な情報を確認させてください。お名前（ふりがな）を教えていただけますか？',
    questionType: 'free_text',
    dataField: 'fullName',
    isRequired: true,
    order: 1,
    aiContext:
      '患者の氏名とふりがなを収集。漢字とひらがなの両方を記録する。括弧やスペースなど様々な表記に対応。',
    validationRules: {
      minLength: 2,
      maxLength: 100,
      pattern: '.+\\(.+\\)|.+（.+）|.+\\s+.+',
    },
    answerExample1: '田中太郎（たなかたろう）です',
    answerExample2: '山田花子（やまだはなこ）',
    answerExample3: '佐藤一郎 さとういちろうです',
    answerExample4: '鈴木美香（すずきみか）と申します',
    answerExample5: '田中太郎です。読み方はたなかたろうです',
  },
  {
    stage: 'basic_info',
    questionKey: 'gender',
    questionText: '性別を教えてください。',
    questionType: 'choice',
    dataField: 'gender',
    isRequired: true,
    order: 2,
    aiContext: '性別を男性・女性・その他から選択。医療記録として正確な記録が必要。',
    validationRules: {
      allowedValues: ['男性', '女性', 'その他'],
    },
    choices: ['男性', '女性', 'その他'],
    answerExample1: '男性です',
    answerExample2: '女性',
    answerExample3: '男',
    answerExample4: 'おとこ',
    answerExample5: 'Male',
  },
  {
    stage: 'basic_info',
    questionKey: 'birth_date',
    questionText: '生年月日を教えてください。西暦でお答えいただけますか？',
    questionType: 'date',
    dataField: 'birthDate',
    isRequired: true,
    order: 3,
    aiContext: '生年月日を西暦で収集。年齢計算に使用。様々な日付形式に対応。',
    validationRules: {
      minDate: '1900-01-01',
      maxDate: '2025-12-31',
      format: 'YYYY-MM-DD',
    },
    answerExample1: '1985年3月15日です',
    answerExample2: '1985/03/15',
    answerExample3: '昭和60年3月15日',
    answerExample4: '1985-3-15',
    answerExample5: '85年3月15日生まれです',
  },
  {
    stage: 'basic_info',
    questionKey: 'address',
    questionText: 'ご住所を教えてください。',
    questionType: 'free_text',
    dataField: 'address',
    isRequired: true,
    order: 4,
    aiContext: '住所情報を収集。感染経路の追跡や緊急時の連絡に使用。',
    validationRules: {
      minLength: 5,
      maxLength: 200,
    },
    answerExample1: '東京都新宿区西新宿1-1-1です',
    answerExample2: '神奈川県横浜市港北区新横浜2-2-2',
    answerExample3: '大阪府大阪市北区梅田1丁目1番1号',
    answerExample4: '愛知県名古屋市中区栄3-3-3マンション101',
    answerExample5: '福岡市博多区博多駅前1-1-1',
  },
  {
    stage: 'basic_info',
    questionKey: 'phone_number',
    questionText: '携帯電話番号を教えてください。',
    questionType: 'free_text',
    dataField: 'phoneNumber',
    isRequired: true,
    order: 5,
    aiContext: '携帯電話番号を収集。緊急連絡や結果通知に使用。ハイフンの有無に対応。',
    validationRules: {
      pattern: '^(0[789]0-?\\d{4}-?\\d{4}|0[789]0\\d{8})$',
      length: [11, 13],
    },
    answerExample1: '090-1234-5678です',
    answerExample2: '08012345678',
    answerExample3: '070-9876-5432',
    answerExample4: '090 1111 2222',
    answerExample5: '携帯は090-5555-6666です',
  },
  {
    stage: 'basic_info',
    questionKey: 'emergency_contact',
    questionText: '緊急連絡先を教えてください。',
    questionType: 'free_text',
    dataField: 'emergencyContact',
    isRequired: true,
    order: 6,
    aiContext: '緊急時の連絡先を収集。関係性と電話番号の両方を記録。',
    validationRules: {
      minLength: 10,
      maxLength: 100,
    },
    answerExample1: '妻の090-8765-4321です',
    answerExample2: '夫090-1111-2222',
    answerExample3: '母親の080-3333-4444',
    answerExample4: '兄の携帯070-5555-6666',
    answerExample5: '緊急連絡先は家族の090-7777-8888です',
  },

  // ============ シーン2: 来院方法・PCR検査希望確認 ============
  {
    stage: 'visit_info',
    questionKey: 'transport_method',
    questionText:
      '本日はどちらの方法でお越しになりましたか？車、自転車、または徒歩のいずれかでお答えください。',
    questionType: 'choice',
    dataField: 'transportMethod',
    isRequired: true,
    order: 1,
    aiContext: '来院方法を確認。感染リスク評価に使用。公共交通機関利用の場合は追加確認が必要。',
    validationRules: {
      allowedValues: ['車', '自転車', '徒歩', '公共交通機関', 'その他'],
    },
    choices: ['車', '自転車', '徒歩', '公共交通機関', 'その他'],
    answerExample1: '車で来ました',
    answerExample2: '自転車です',
    answerExample3: '歩いて来ました',
    answerExample4: '電車とバスで来ました',
    answerExample5: 'マイカーで来院しました',
  },
  {
    stage: 'visit_info',
    questionKey: 'pcr_test_desired',
    questionText: 'PCR検査をご希望されますか？',
    questionType: 'boolean',
    dataField: 'pcrTestDesired',
    isRequired: true,
    order: 2,
    aiContext: 'PCR検査の希望を確認。検査の必要性と患者の希望を記録。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'はい、希望します',
    answerExample2: 'PCR検査をお願いします',
    answerExample3: 'いいえ、今回は結構です',
    answerExample4: '検査したいです',
    answerExample5: '特に希望しません',
  },

  // ============ シーン3: 体温・バイタルサイン ============
  {
    stage: 'vitals',
    questionKey: 'height',
    questionText: '身長を教えてください。',
    questionType: 'number',
    dataField: 'height',
    isRequired: true,
    order: 1,
    aiContext: '身長をcm単位で記録。BMI計算に使用。100-250cmの範囲で入力。',
    validationRules: {
      min: 100,
      max: 250,
      unit: 'cm',
    },
    answerExample1: '175cmです',
    answerExample2: '160センチ',
    answerExample3: '身長は170cm',
    answerExample4: '1メートル65センチ',
    answerExample5: '180',
  },
  {
    stage: 'vitals',
    questionKey: 'weight',
    questionText: '体重を教えてください。',
    questionType: 'number',
    dataField: 'weight',
    isRequired: true,
    order: 2,
    aiContext: '体重をkg単位で記録。BMI計算に使用。30-200kgの範囲で入力。',
    validationRules: {
      min: 30,
      max: 200,
      unit: 'kg',
    },
    answerExample1: '70kgです',
    answerExample2: '65キロ',
    answerExample3: '体重は55kg',
    answerExample4: '80キログラム',
    answerExample5: '62',
  },
  {
    stage: 'vitals',
    questionKey: 'morning_temperature',
    questionText: '本日朝に測った体温を教えてください。',
    questionType: 'number',
    dataField: 'morningTemperature',
    isRequired: true,
    order: 3,
    aiContext: '朝の体温を記録。発熱の経過を把握。35-42度の範囲で小数点1位まで。',
    validationRules: {
      min: 35.0,
      max: 42.0,
      decimalPlaces: 1,
      unit: '℃',
    },
    answerExample1: '38.2度でした',
    answerExample2: '37.5℃',
    answerExample3: '朝は36.8度',
    answerExample4: '38度2分',
    answerExample5: 'あさ測ったら38.5℃でした',
  },
  {
    stage: 'vitals',
    questionKey: 'current_temperature',
    questionText: '来院時に測定した体温もお教えください。',
    questionType: 'number',
    dataField: 'currentTemperature',
    isRequired: true,
    order: 4,
    aiContext: '来院時の体温を記録。現在の発熱状況を把握。35-42度の範囲で小数点1位まで。',
    validationRules: {
      min: 35.0,
      max: 42.0,
      decimalPlaces: 1,
      unit: '℃',
    },
    answerExample1: 'さっき測ったら38.5度でした',
    answerExample2: '今は39.1℃です',
    answerExample3: '来院時は38.8度',
    answerExample4: '38度5分',
    answerExample5: 'いま計ったら38.3℃',
  },
  {
    stage: 'vitals',
    questionKey: 'fever_start_date',
    questionText: '発熱はいつ頃から始まりましたか？',
    questionType: 'free_text',
    dataField: 'feverStartDate',
    isRequired: true,
    order: 5,
    aiContext: '発熱開始時期を記録。感染のタイミングや経過を把握。相対的な時間表現に対応。',
    validationRules: {
      maxLength: 100,
    },
    answerExample1: '昨日の夕方からです',
    answerExample2: '2日前の夜から',
    answerExample3: '今朝から熱が出始めました',
    answerExample4: '3日前ぐらいから',
    answerExample5: '一昨日のお昼頃から発熱しています',
  },

  // ============ シーン4: 症状確認 ============
  {
    stage: 'symptoms',
    questionKey: 'current_symptoms',
    questionText:
      '現在の症状について確認いたします。咳、鼻水、喉の痛み、関節痛、味覚異常、嗅覚異常、腹痛、下痢、呼吸苦、倦怠感、頭痛、めまいの中で当てはまるものがあれば教えてください。',
    questionType: 'choice',
    dataField: 'symptoms',
    isRequired: true,
    order: 1,
    aiContext: '現在の症状を複数選択で収集。COVID-19の症状に焦点を当てた確認。',
    validationRules: {
      allowMultiple: true,
      allowNone: true,
    },
    choices: [
      '咳',
      '鼻水',
      '喉の痛み',
      '関節痛',
      '味覚異常',
      '嗅覚異常',
      '腹痛',
      '下痢',
      '呼吸苦',
      '倦怠感',
      '頭痛',
      'めまい',
      'その他',
      '特になし',
    ],
    answerExample1: '咳と喉の痛み、それから倦怠感があります',
    answerExample2: '頭痛も少しあります',
    answerExample3: '咳、鼻水、関節痛です',
    answerExample4: '特にありません',
    answerExample5: '咳がひどくて、だるい感じがします',
  },
  {
    stage: 'symptoms',
    questionKey: 'other_symptoms',
    questionText: 'その他に何か気になる症状はございますか？',
    questionType: 'free_text',
    dataField: 'otherSymptoms',
    isRequired: false,
    order: 2,
    aiContext: 'リストにない症状や詳細な症状の説明を自由記述で収集。',
    validationRules: {
      maxLength: 300,
    },
    answerExample1: '特にありません',
    answerExample2: '少し息苦しい感じがします',
    answerExample3: '食欲がありません',
    answerExample4: '夜眠れないことがあります',
    answerExample5: '時々胸が痛くなります',
  },

  // ============ シーン5: 新型コロナワクチン接種歴 ============
  {
    stage: 'vaccination',
    questionKey: 'vaccination_count',
    questionText: '新型コロナワクチンの接種歴について確認させてください。何回接種されていますか？',
    questionType: 'number',
    dataField: 'vaccinationCount',
    isRequired: true,
    order: 1,
    aiContext: 'ワクチン接種回数を確認。0-10回程度の範囲。接種歴により症状の重篤度が変わる可能性。',
    validationRules: {
      min: 0,
      max: 10,
    },
    answerExample1: '4回接種しています',
    answerExample2: '3回です',
    answerExample3: 'まだ打っていません',
    answerExample4: '5回目まで受けました',
    answerExample5: '2回だけです',
  },
  {
    stage: 'vaccination',
    questionKey: 'vaccination_1st',
    questionText:
      '1回目の接種日とワクチンの種類を教えてください。ファイザー、モデルナ、その他のいずれかでお答えください。',
    questionType: 'free_text',
    dataField: 'vaccination1st',
    isRequired: false,
    order: 2,
    aiContext: '1回目のワクチン接種情報。日付とワクチン種類の両方を記録。',
    validationRules: {
      maxLength: 100,
    },
    answerExample1: '2021年6月15日にファイザーです',
    answerExample2: '2021/7/10 モデルナ',
    answerExample3: 'ファイザーを去年の夏に',
    answerExample4: '2021年5月頃、ファイザー製',
    answerExample5: 'まだ接種していません',
    followUpConditions: {
      dependency: 'vaccination_count',
      condition: 'greaterThan',
      value: 0,
    },
  },
  {
    stage: 'vaccination',
    questionKey: 'vaccination_2nd',
    questionText: '2回目はいかがでしょうか？',
    questionType: 'free_text',
    dataField: 'vaccination2nd',
    isRequired: false,
    order: 3,
    aiContext: '2回目のワクチン接種情報。1回目と同様に日付とワクチン種類を記録。',
    validationRules: {
      maxLength: 100,
    },
    answerExample1: '2021年7月20日、これもファイザーです',
    answerExample2: '2021/8/15 ファイザー',
    answerExample3: '1回目の3週間後、同じファイザー',
    answerExample4: '7月末にファイザー2回目',
    answerExample5: '2回目は受けていません',
    followUpConditions: {
      dependency: 'vaccination_count',
      condition: 'greaterThan',
      value: 1,
    },
  },
  {
    stage: 'vaccination',
    questionKey: 'vaccination_latest',
    questionText: '最後に接種されたワクチンの日付と種類を教えてください。',
    questionType: 'free_text',
    dataField: 'vaccinationLatest',
    isRequired: false,
    order: 4,
    aiContext: '最新のワクチン接種情報。免疫状態の評価に重要。',
    validationRules: {
      maxLength: 100,
    },
    answerExample1: '2022年6月5日、ファイザーです',
    answerExample2: '今年の春、モデルナ',
    answerExample3: '2023年10月にファイザー',
    answerExample4: '半年前にオミクロン対応ワクチン',
    answerExample5: '昨年末にブースター接種',
    followUpConditions: {
      dependency: 'vaccination_count',
      condition: 'greaterThan',
      value: 2,
    },
  },

  // ============ シーン6: 接触歴・渡航歴 ============
  {
    stage: 'contact_history',
    questionKey: 'suspected_contact',
    questionText: '2週間以内に新型コロナ感染症を疑う方と接触されましたか？',
    questionType: 'boolean',
    dataField: 'suspectedContact',
    isRequired: true,
    order: 1,
    aiContext: '感染疑いのある人との接触歴を確認。感染経路の特定に重要。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、していません',
    answerExample2: 'はい、職場で感染者が出ました',
    answerExample3: '家族に症状がある人がいます',
    answerExample4: '特に心当たりはありません',
    answerExample5: '友人が後から陽性になりました',
  },
  {
    stage: 'contact_history',
    questionKey: 'close_contact',
    questionText: '濃厚接触者に該当しますか？',
    questionType: 'boolean',
    dataField: 'closeContact',
    isRequired: true,
    order: 2,
    aiContext: '保健所定義の濃厚接触者該当性を確認。検査や隔離の必要性判断。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: '該当しません',
    answerExample2: 'はい、保健所から連絡がありました',
    answerExample3: 'よくわかりません',
    answerExample4: '同居家族が陽性でした',
    answerExample5: '濃厚接触者ではないと思います',
  },
  {
    stage: 'contact_history',
    questionKey: 'overseas_travel',
    questionText: '2週間以内に海外への渡航歴はありますか？',
    questionType: 'boolean',
    dataField: 'overseasTravel',
    isRequired: true,
    order: 3,
    aiContext: '海外渡航歴を確認。変異株への感染リスク評価に使用。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、ありません',
    answerExample2: 'はい、先週アメリカに行きました',
    answerExample3: '海外には行っていません',
    answerExample4: '出張でタイに行きました',
    answerExample5: '旅行はしていません',
  },
  {
    stage: 'contact_history',
    questionKey: 'travel_contact',
    questionText: '渡航歴のある方との接触はありましたか？',
    questionType: 'boolean',
    dataField: 'travelContactHistory',
    isRequired: true,
    order: 4,
    aiContext: '海外渡航者との接触歴を確認。間接的な海外株への曝露リスク評価。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、ありません',
    answerExample2: '同僚が海外出張から帰って来ました',
    answerExample3: '特に心当たりはありません',
    answerExample4: '家族が海外旅行に行きました',
    answerExample5: '渡航歴のある人との接触はありません',
  },

  // ============ シーン7: 他院受診歴 ============
  {
    stage: 'medical_history',
    questionKey: 'other_hospital_visit',
    questionText: 'この症状について、他の医療機関を受診されましたか？',
    questionType: 'boolean',
    dataField: 'otherHospitalVisit',
    isRequired: true,
    order: 1,
    aiContext: '同症状での他院受診歴を確認。重複受診や処方薬の把握に必要。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、受診していません',
    answerExample2: 'はい、昨日内科に行きました',
    answerExample3: '今回が初めてです',
    answerExample4: 'かかりつけ医に診てもらいました',
    answerExample5: '他の病院には行っていません',
  },

  // ============ シーン8: 既往歴・治療歴 ============
  {
    stage: 'medical_history',
    questionKey: 'chronic_treatment',
    questionText: '慢性の病気で現在治療を受けていらっしゃいますか？',
    questionType: 'boolean',
    dataField: 'chronicTreatment',
    isRequired: true,
    order: 2,
    aiContext: '慢性疾患での治療状況を確認。COVID-19重症化リスク評価に重要。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'はい、高血圧で内科に通院しています',
    answerExample2: '糖尿病の治療を受けています',
    answerExample3: 'いいえ、特にありません',
    answerExample4: '血圧の薬を飲んでいます',
    answerExample5: '定期的な治療は受けていません',
  },
  {
    stage: 'medical_history',
    questionKey: 'treatment_details',
    questionText: 'どちらの病院の何科で治療を受けていらっしゃいますか？',
    questionType: 'free_text',
    dataField: 'treatmentDetails',
    isRequired: false,
    order: 3,
    aiContext: '治療中の疾患詳細と医療機関情報を記録。連携が必要な場合の参考。',
    validationRules: {
      maxLength: 200,
    },
    answerExample1: '新宿クリニックの内科です',
    answerExample2: '○○総合病院の循環器科',
    answerExample3: '近所の内科医院で高血圧の治療',
    answerExample4: '大学病院の糖尿病外来',
    answerExample5: 'かかりつけ医で定期受診',
    followUpConditions: {
      dependency: 'chronic_treatment',
      condition: 'equals',
      value: true,
    },
  },
  {
    stage: 'medical_history',
    questionKey: 'hospital_history',
    questionText: '当院での既往歴はございますか？',
    questionType: 'boolean',
    dataField: 'previousHospitalHistory',
    isRequired: true,
    order: 4,
    aiContext: '当院での受診歴を確認。過去のカルテとの照合に使用。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、ありません',
    answerExample2: 'はい、以前にも受診しました',
    answerExample3: '初診です',
    answerExample4: '何年か前に来たことがあります',
    answerExample5: '当院は初めてです',
  },
  {
    stage: 'medical_history',
    questionKey: 'surgery_history',
    questionText: '過去に大きな病気のために入院や手術を受けたことはありますか？',
    questionType: 'boolean',
    dataField: 'surgeryHistory',
    isRequired: true,
    order: 5,
    aiContext: '重大な既往歴を確認。免疫状態や併存疾患の評価に重要。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、ありません',
    answerExample2: 'はい、盲腸の手術をしました',
    answerExample3: '大きな病気はしていません',
    answerExample4: '昔、胆石の手術を受けました',
    answerExample5: '入院や手術の経験はありません',
  },

  // ============ シーン9: 服薬・アレルギー歴 ============
  {
    stage: 'medication_allergy',
    questionKey: 'otc_medication',
    questionText: '市販薬の服用はありますか？',
    questionType: 'boolean',
    dataField: 'overtcMedication',
    isRequired: true,
    order: 1,
    aiContext: '市販薬の服用状況を確認。薬物相互作用や症状への影響を評価。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'はい、昨夜解熱剤を飲みました',
    answerExample2: '風邪薬を飲んでいます',
    answerExample3: 'いいえ、何も飲んでいません',
    answerExample4: '鎮痛剤を服用しました',
    answerExample5: '市販薬は使っていません',
  },
  {
    stage: 'medication_allergy',
    questionKey: 'medication_details',
    questionText: 'どのようなお薬を服用されましたか？',
    questionType: 'free_text',
    dataField: 'medicationDetails',
    isRequired: false,
    order: 2,
    aiContext: '服用した市販薬の詳細を記録。成分名や商品名を可能な限り特定。',
    validationRules: {
      maxLength: 200,
    },
    answerExample1: 'ロキソニンです',
    answerExample2: 'バファリンを飲みました',
    answerExample3: 'カロナール',
    answerExample4: '解熱鎮痛剤（名前は覚えていません）',
    answerExample5: '風邪薬のパブロン',
    followUpConditions: {
      dependency: 'otc_medication',
      condition: 'equals',
      value: true,
    },
  },
  {
    stage: 'medication_allergy',
    questionKey: 'drug_allergies',
    questionText:
      '過去に飲み薬や注射でアレルギー（発疹、気分が悪いなど）を起こしたことがありますか？',
    questionType: 'boolean',
    dataField: 'allergies',
    isRequired: true,
    order: 3,
    aiContext: '薬物アレルギー歴を確認。処方薬の安全性確保に重要。重篤な反応の可能性評価。',
    validationRules: {
      acceptedValues: [true, false],
    },
    answerExample1: 'いいえ、ありません',
    answerExample2: 'はい、ペニシリンでじんましんが出ました',
    answerExample3: 'アレルギーはありません',
    answerExample4: '以前、抗生物質で発疹が出ました',
    answerExample5: '薬でアレルギーを起こしたことはありません',
  },
  {
    stage: 'medication_allergy',
    questionKey: 'allergy_details',
    questionText: 'どのようなお薬でどのような症状が出ましたか？',
    questionType: 'free_text',
    dataField: 'allergyDetails',
    isRequired: false,
    order: 4,
    aiContext: 'アレルギーの詳細情報を記録。薬剤名と症状の関連を明確化。',
    validationRules: {
      maxLength: 300,
    },
    answerExample1: 'ペニシリンで全身にじんましんが出ました',
    answerExample2: '鎮痛剤で胃が痛くなります',
    answerExample3: '抗生物質で下痢をしました',
    answerExample4: '造影剤で気分が悪くなりました',
    answerExample5: '詳しくは覚えていませんが発疹が出ました',
    followUpConditions: {
      dependency: 'drug_allergies',
      condition: 'equals',
      value: true,
    },
  },

  // ============ シーン10: 生活習慣 ============
  {
    stage: 'lifestyle',
    questionKey: 'drinking_habits',
    questionText: 'お酒は飲まれますか？',
    questionType: 'choice',
    dataField: 'drinkingHabits',
    isRequired: true,
    order: 1,
    aiContext: '飲酒習慣を確認。免疫機能や肝機能への影響評価。治療方針の参考。',
    validationRules: {
      allowedValues: ['飲む', '飲まない', '時々飲む', '以前は飲んでいた'],
    },
    choices: ['飲む', '飲まない', '時々飲む', '以前は飲んでいた'],
    answerExample1: '飲みます',
    answerExample2: '週に2-3回、ビール1-2本程度です',
    answerExample3: 'お酒は飲みません',
    answerExample4: '時々付き合い程度に',
    answerExample5: '以前は飲んでいましたが今は飲みません',
  },
  {
    stage: 'lifestyle',
    questionKey: 'drinking_frequency',
    questionText: 'どのくらいの頻度と量でしょうか？',
    questionType: 'free_text',
    dataField: 'drinkingFrequency',
    isRequired: false,
    order: 2,
    aiContext: '飲酒の頻度と量を詳細に記録。健康リスクの評価に使用。',
    validationRules: {
      maxLength: 100,
    },
    answerExample1: '週に2-3回、ビール1-2本程度です',
    answerExample2: '毎日日本酒2合',
    answerExample3: '月に数回程度',
    answerExample4: '週末にワインを1-2杯',
    answerExample5: '仕事の付き合いで月2-3回',
    followUpConditions: {
      dependency: 'drinking_habits',
      condition: 'notEquals',
      value: '飲まない',
    },
  },
  {
    stage: 'lifestyle',
    questionKey: 'smoking_habits',
    questionText: 'タバコは吸われますか？',
    questionType: 'choice',
    dataField: 'smokingHabits',
    isRequired: true,
    order: 3,
    aiContext: '喫煙状況を確認。COVID-19重症化リスクや呼吸器症状への影響評価。',
    validationRules: {
      allowedValues: ['吸う', '吸わない', '禁煙した', '以前は吸っていた'],
    },
    choices: ['吸う', '吸わない', '禁煙した', '以前は吸っていた'],
    answerExample1: '禁煙しました',
    answerExample2: 'タバコは吸いません',
    answerExample3: '現在も吸っています',
    answerExample4: '3年前にやめました',
    answerExample5: '以前は吸っていましたが今は吸いません',
  },
  {
    stage: 'lifestyle',
    questionKey: 'smoking_history',
    questionText: 'いつ頃から禁煙されましたか？また、以前はどのくらい吸っていらっしゃいましたか？',
    questionType: 'free_text',
    dataField: 'smokingHistory',
    isRequired: false,
    order: 4,
    aiContext: '喫煙歴の詳細を記録。禁煙期間と過去の喫煙量で呼吸器リスクを評価。',
    validationRules: {
      maxLength: 200,
    },
    answerExample1: '3年前から禁煙しました。以前は1日20本、20年間吸っていました',
    answerExample2: '5年前にやめました。1日1箱を15年間',
    answerExample3: '昨年禁煙。1日10本程度を10年間',
    answerExample4: '2年前から禁煙。以前は1日半箱程度',
    answerExample5: '禁煙して1年。20年間1日1-2箱吸っていました',
    followUpConditions: {
      dependency: 'smoking_habits',
      condition: 'in',
      value: ['禁煙した', '以前は吸っていた'],
    },
  },
];
