export const GAME_LOGICAL_WIDTH = 320;
export const GAME_LOGICAL_HEIGHT = 192;
export const GAME_RENDER_SCALE = 3;

export const GAME_CANVAS_WIDTH = GAME_LOGICAL_WIDTH * GAME_RENDER_SCALE;
export const GAME_CANVAS_HEIGHT = GAME_LOGICAL_HEIGHT * GAME_RENDER_SCALE;

export const GAME_TEXT_RESOLUTION = GAME_RENDER_SCALE;
