import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

type Position = [number, number];
type Polygon = Position[][];
type Geometry =
	| { type: "Polygon"; coordinates: Polygon }
	| { type: "MultiPolygon"; coordinates: Polygon[] };
type Feature = {
	type: "Feature";
	properties: { ISO_A2_EH?: unknown; NAME?: unknown };
	geometry: Geometry;
};
type FeatureCollection = { type: "FeatureCollection"; features: Feature[] };

const [, , inputPath, outputPath, regionIdsPath] = process.argv;
if (!inputPath || !outputPath || !regionIdsPath) {
	throw new Error(
		"usage: bun scripts/build-dashboard-world-outline.ts <input.geojson> <output.json> <region-ids.ts>",
	);
}

const input = readFileSync(inputPath);
const source = JSON.parse(input.toString("utf8")) as FeatureCollection;
if (source.type !== "FeatureCollection" || !Array.isArray(source.features))
	throw new Error("input must be a GeoJSON FeatureCollection");

const format = (value: number) =>
	Number(value.toFixed(2)).toString().replace("-0", "0");
const project = ([longitude, latitude]: Position) => {
	if (
		!Number.isFinite(latitude) ||
		!Number.isFinite(longitude) ||
		latitude < -90 ||
		latitude > 90 ||
		longitude < -180 ||
		longitude > 180
	)
		throw new Error("GeoJSON contains an invalid coordinate");
	return [((longitude + 180) / 360) * 1_000, ((90 - latitude) / 180) * 500];
};
const ringPath = (ring: Position[]) =>
	`${ring
		.map((position, index) => {
			const [x, y] = project(position);
			return `${index === 0 ? "M" : "L"}${format(x)} ${format(y)}`;
		})
		.join("")}Z`;
const geometryPath = (geometry: Geometry) => {
	const polygons =
		geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
	return polygons.flatMap((polygon) => polygon.map(ringPath)).join("");
};

const paths: Record<string, string> = {};
for (const feature of source.features) {
	const regionId = String(feature.properties.ISO_A2_EH ?? "").toUpperCase();
	if (!/^[A-Z]{2}$/.test(regionId)) continue;
	if (paths[regionId]) throw new Error(`duplicate ISO region: ${regionId}`);
	paths[regionId] = geometryPath(feature.geometry);
}
const order = Object.keys(paths).sort();
if (order.length < 170) throw new Error("too few ISO regions in source data");
const generated = {
	viewBox: "0 0 1000 500",
	order,
	paths: Object.fromEntries(
		order.map((regionId) => [regionId, paths[regionId]]),
	),
};
writeFileSync(outputPath, `${JSON.stringify(generated)}\n`);
writeFileSync(
	regionIdsPath,
	`/* Generated by scripts/build-dashboard-world-outline.ts. */\nexport const WORLD_110M_REGION_IDS = ${JSON.stringify(order)} as const;\n`,
);
const output = readFileSync(outputPath);
const digest = (value: Buffer) =>
	createHash("sha256").update(value).digest("hex");
process.stdout.write(
	`${order.length} regions; source sha256=${digest(input)}; output sha256=${digest(output)}\n`,
);
