import { type DashboardDataFrameV2, standardFieldConfigV2Schema } from "@shared/schemas/dashboard.schema";
import { describe, expect, it } from "vitest";
import { previewFrameRows, sanitizeInspectorResponse } from "../inspector/sanitize";
import { layoutsFromManifest } from "../layout/layout";
import { resolveDashboardLinkV2 } from "../links/resolve-link";
import { dashboardPanelV2QueryKey, stableJson } from "../query-keys";
import { reconcileVariableFilters } from "../variables";
import { toCategoryRows } from "../visualizations/core-bar/model";
import { toTimeseriesRows } from "../visualizations/core-timeseries/model";
import { resolveFieldConfig } from "./field-config";
import { frameRowCount, selectPanelFrames } from "./frame-selection";
import { derivePanelState } from "./panel-state";
import { createDashboardTheme, resolveThemeColor } from "./theme";

// @ts-expect-error The fixture intentionally switches discriminated field shapes at runtime.
const frame = (refId: string, shapeHint: "table" | "category" | "timeseries" = "table"): DashboardDataFrameV2 => ({ schemaVersion: 2, refId, source: { kind: "query", refId }, name: refId, fields: [{ key: shapeHint === "timeseries" ? "time" : shapeHint === "category" ? "category" : "value", label: "Value", type: shapeHint === "timeseries" ? "time" : shapeHint === "category" ? "string" : "number", values: shapeHint === "timeseries" ? [1000, 2000] : shapeHint === "category" ? ["a", "b"] : [1, 2], roles: shapeHint === "timeseries" ? ["time"] : shapeHint === "category" ? ["category"] : ["value"], labels: {} }, ...(shapeHint === "timeseries" ? [{ key: "count", label: "Count", type: "number" as const, values: [1, 2], roles: ["value" as const], labels: {} }] : shapeHint === "category" ? [{ key: "count", label: "Count", type: "number" as const, values: [1, 2], roles: ["value" as const], labels: {} }] : [])], meta: { shapeHint } });
const panel = { visualization: { fieldConfig: standardFieldConfigV2Schema.parse({}), overrides: [], frameRefs: ["A"], type: "core.table", options: {}, tableFallback: { enabled: true, defaultView: "visualization" } } } as never;

describe("dashboard v2 helpers", () => {
	it("creates stable query keys and selects frames", () => { expect(stableJson({ b: 1, a: [2, 1], empty: null })).toBe('{"a":[2,1],"b":1,"empty":null}'); expect(stableJson("x")).toBe('"x"'); expect(dashboardPanelV2QueryKey("d", "p", { schemaVersion: 2, range: { kind: "relative", value: "1h" }, timezone: "UTC", filters: {}, maxDataPoints: 1, maxRows: 1 })[0]).toBe("dashboard-v2"); expect(frameRowCount(frame("A"))).toBe(2); expect(frameRowCount({ ...frame("empty"), fields: [] })).toBe(0); expect(selectPanelFrames(panel, [frame("B"), frame("A")]).map((item) => item.refId)).toEqual(["A"]); expect(selectPanelFrames(panel, [frame("B")])).toEqual([]); });
	it("reconciles required variables and derives state priority", () => { const pending = reconcileVariableFilters({ variables: [{ id: "service", label: "Service", selection: "single", required: true, defaultValues: ["api"], dependsOn: [], source: { kind: "static" } }], panels: [] } as never, [{ isPending: true }], { service: ["api"] }); expect(pending.filters).toEqual({ service: ["api"] }); expect(pending.panelsReady).toBe(false); const result = reconcileVariableFilters({ variables: [{ id: "service", label: "Service", selection: "multiple", required: true, defaultValues: [], dependsOn: [], source: { kind: "query", queryId: "q" } }], panels: [] } as never, [{ schemaVersion: 2, variableId: "service", options: [{ value: "disabled", label: "Disabled", disabled: true }, { value: "prod", label: "Production", disabled: false }] }], { service: ["disabled"] }); expect(result.filters).toEqual({ service: ["prod"] }); expect(result.panelsReady).toBe(true); expect(derivePanelState({ isPending: true, hasData: false })).toBe("loading"); expect(derivePanelState({ isPending: false, hasData: false, emptyReason: "none" })).toBe("empty"); expect(derivePanelState({ isPending: false, hasData: true, partial: true })).toBe("partial"); expect(derivePanelState({ isPending: false, hasData: true })).toBe("ready"); expect(derivePanelState({ isPending: false, hasData: true, error: new Error("x") })).toBe("ready"); expect(derivePanelState({ isPending: false, hasData: true, incompatible: true })).toBe("incompatible"); });
	it("resolves field config, theme and renderer models", () => { const valueFrame = frame("A"); expect(resolveFieldConfig(panel, valueFrame, valueFrame.fields[0]!).unit.kind).toBe("none"); expect(resolveThemeColor("--color-muted")).toBe("var(--color-muted)"); expect(resolveThemeColor("--not-allowed")).toBe("var(--color-brand)"); expect(createDashboardTheme().palette.length).toBeGreaterThan(0); expect(toTimeseriesRows([frame("A", "timeseries")])).toHaveLength(2); expect(toTimeseriesRows([])).toEqual([]); expect(toCategoryRows([frame("A", "category")])).toHaveLength(2); expect(toCategoryRows([])).toEqual([]); });
	it("sanitizes inspector and resolves same-origin links", () => { const response = { schemaVersion: 2 as const, requestId: "11111111-1111-4111-8111-111111111111", generatedAt: "2026-07-16T00:00:00.000Z", resolvedRange: { from: "2026-07-16T00:00:00.000Z", to: "2026-07-16T01:00:00.000Z" }, durationMs: 1, counts: { frames: 1, fields: 1, rows: 2, cells: 2 }, state: { partial: false, truncated: false, notices: [] }, frames: [frame("A")] } as never; expect(sanitizeInspectorResponse(undefined)).toBeNull(); expect(sanitizeInspectorResponse(response)?.frames[0]?.fields[0]?.rowCount).toBe(2); expect(previewFrameRows(frame("A"))).toHaveLength(2); expect(previewFrameRows(frame("A"), 1)).toHaveLength(1); expect(resolveDashboardLinkV2({ id: "l", title: "Protected", targetId: "protected", to: "/protected", search: { field: { kind: "field", fieldKey: "value" }, filter: { kind: "filter", variableId: "region", format: "comma" }, first: { kind: "filter", variableId: "region", format: "first" }, json: { kind: "filter", variableId: "region", format: "json" }, constant: { kind: "constant", value: "x" }, from: { kind: "dashboard-range-from" }, toValue: { kind: "dashboard-range-to" }, frame: { kind: "frame-ref" } }, includeRange: true, includeFilters: true, openInNewTab: true }, { region: ["apac", "us"] }, { kind: "absolute", from: "2026-07-16T00:00:00.000Z", to: "2026-07-16T01:00:00.000Z" }, { value: 42 }, "A")).toMatchObject({ to: "/protected", openInNewTab: true, search: { field: "42", filter: "apac,us", first: "apac", json: '["apac","us"]', constant: "x", from: "2026-07-16T00:00:00.000Z", toValue: "2026-07-16T01:00:00.000Z", frame: "A", range: "2026-07-16T00:00:00.000Z,2026-07-16T01:00:00.000Z" } }); expect(resolveDashboardLinkV2({ id: "bad", title: "Bad", targetId: "unknown", to: "/unknown", search: {}, includeRange: false, includeFilters: false, openInNewTab: false }, {}, { kind: "relative", value: "1h" }, {})).toBeNull(); });
	it("builds responsive layouts", () => { const result = layoutsFromManifest({ id: "d", schemaVersion: 2, revision: 1, title: "D", description: "", layoutVersion: 1, defaultRange: { kind: "relative", value: "1h" }, defaultTimezone: "UTC", defaultRefreshSeconds: 0, variables: [], panels: [{ id: "p", title: "P", description: "", layout: { x: 0, y: 0, w: 12, h: 2, minW: 1, minH: 1 }, queries: [{ refId: "A", queryId: "q", outputFrameRefs: ["A"], hidden: false }], transformations: [], visualization: { type: "core.table", frameRefs: ["A"], options: {}, fieldConfig: standardFieldConfigV2Schema.parse({}), overrides: [], tableFallback: { enabled: true, defaultView: "visualization" } }, accessibleLabel: "P", links: [] }], inspectorEnabled: false }); expect(result.xs[0]?.w).toBe(1); });
});
